#!/bin/bash

#######################################################
### Created by khan on Mon Feb 27 23:03:58 CST 2012 ###
#######################################################

###################### Help Text ######################
# Usage: AddHeader

#######################################################
if (( $# < 0 )) || [[ "$1" == --help ]]; then echo
sed -n "/^# Usa/,/^##*$/p" $0 | tr -d "#"; exit 0; fi
#######################################################

## Initialize
pFile="$1"
pTemp=`TempFile AddHeader`

## Functions

## Main
wc -l $pFile | word 1 > $pTemp
cat $pFile >> $pTemp
mv $pTemp $pFile
