#!/bin/bash

#######################################################
### Created by khan on Wed Jul 6 12:01:48 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: atIRC
#######################################################
if isHelp 0 $0 "$@"; then exit 0; fi

case $1 in
	IRC|irc)
		whatsmyip | grep -q 146.6.162
		exit $?
	;;
	campus)
		whatsmyip | grep -q 128.83.136
		exit $?
	;;
esac
