#!/bin/bash

#######################################################
### Created by khan on Wed Aug 10 13:10:35 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: CalWin <window> <w h x y>
#######################################################
if (( $# < 0 )) || [[ "$1" == *-h* ]]; then echo
	grep -A 99999 "# Help.*#*" $0 |\
	grep -E -m 2 -B 99999 "#{10,}"; echo; exit 0
fi
#######################################################

sWin="$1"; shift
viDesired=$@

viReceived=`WinGeo "$sWin"`

CalGeo $viDesired $viReceived > calibration
