#!/bin/bash

#######################################################
### Created by khan on Sat Jul 9 10:15:33 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: Cap
#######################################################
if isHelp 0 $0 "$@"; then exit 0; fi

if [ $# -gt 0 ]; then echo $@ | Cap; fi

if pipe; then
	awk '{printf("%s%s\n",toupper(substr($0,1,1)),substr($0,2))}' /dev/stdin
fi
