#!/bin/bash

#######################################################
### Created by khan on Sat Jul 2 12:55:48 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: Combinations
#######################################################
if isHelp 0 $0 "$@"; then exit 0; fi

if [[ $1 == -d ]]; then 
	sDelim=$2; shift 2
else
	sDelim=""
fi

for file in "$@"; do
	

awk '
{
   file_count++;
   rec_num = 0;
   while (getline rec <$0)
     records[file_count, ++rec_num] = rec;
   close($0);
   records[file_count, "count"] = rec_num;
}

function comb_file(file_num, rec, rec_count, r) {
   if (file_num > file_count) {
      print rec;
   } else {
      rec_count = records[file_num, "count"];
      for (r=1; r<=rec_count; r++)
         comb_file(file_num+1, rec (file_num>1 ? "'"$sDelim"'" : "") records[file_num, r]);
   }
}

END {
   rec = "";
   comb_file(1, rec);
}

' file_order.txt		
