#!/bin/bash

#####################################################
## Created by khan on Fri Apr 15 18:25:00 EDT 2011 ##
#####################################################

if [ $# == 0 ]; then
	 echo "Usage: $0" 
	 exit 0
fi

if [ $1 == vncc ]; then
	cd $HOME/bin

	mkdir vncd
	cp vncc vncdaemon waituntilwindowopen windowopen vncd/
	scp -r vncd sandstone:export/software/TigerVNC/

