#!/bin/bash

#######################################################
### Created by khan on Sun Jul 3 20:22:43 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: con
#######################################################
if isHelp 0 $0 "$@"; then exit 0; fi

if regmatch "$@" ' \? '; then
	eval `echo "$@" | sed -e 's/^\(.*\) ? \(.*\) : \(.*\)$/if \1; then echo \2; else echo \3; fi/'`
else
	eval `echo "$@" | sed -e 's/\(.*\) \([^ ]*\) : \(.*\)/if \1 \2; then echo \2; else echo \3; fi/'`
fi
