#!/bin/bash
dir=`pwd`
flags="-avzHu $@ --exclude '*~' -e ssh"
host="khan@faraday.ph.utexas.edu"
echo Uploading from $dir to $host...
#echo rsync $flags $dir $host:`dirname $dir`
rsync $flags $dir $host:`dirname $dir`

