#!/bin/bash

#######################################################
### Created by khan on Tue May 10 14:32:46 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: ddns-check [-q]
#######################################################
if (( $# < 0 )) || [[ "$1" == *-h* ]]; then echo
	grep -A 99999 "# Help.*#*" $0 |\
	grep -E -m 2 -B 99999 "#{10,}"
echo; exit 0; fi
#######################################################

iMyIp=`whatsmyip ddns`

if [ "$1" != "-q" ]; then echo "$iMyIp"; fi

if (( `whatsmyip ddns | awk '{print $2}' | uniq | wc -l` == 1 )); then
	exit 0
else
	exit 1
fi

