#!/bin/bash

#####################################################
## Created by khan on Tue Jun  7 21:26:57 CDT 2011 ##
#####################################################

################# Help Text ##################
script=`basename $0`
Usage="Usage: $script"
if isHelp 0 $0 "$@"; then echo $Usage; exit 0; fi
##############################################

if [ "$1" ]; then echo "$1"; else echo "$2"; fi

