#!/bin/bash

#######################################################
### Created by khan on Sun Jul 17 23:07:56 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: Derivatives
#######################################################
if (( $# < 0 )) || [[ "$1" == *-h* ]]; then echo
	grep -A 99999 "# Help.*#*" $0 |\
	grep -E -m 2 -B 99999 "#{10,}"
echo; exit 0; fi
#######################################################

sDelim=${1:-' '}

x=`TempFile x`
v=`TempFile v`
a=`TempFile a`

tee > $x
cat $x | Delta > $v
cat $v | Delta > $a
	
paste -d "$sDelim" $x $v $a
fi
