#!/bin/bash

#######################################################
### Created by khan on Sat Jul 16 10:00:21 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: DirSize
#######################################################
if (( $# < 0 )) || [[ "$1" == *-h* ]]; then echo
	grep -A 99999 "# Help.*#*" $0 |\
	grep -E -m 2 -B 99999 "#{10,}"
echo; exit 0; fi
#######################################################

file=/tmp/dsize

du -m --max-depth 1 2>/dev/null | sort -n | sed 's,\./,,g' >$file

head -n -1 $file

if [[ $1 == -t ]]; then
	sLast=`tail -n 1 $file | sed 's/\./TOTAL/g'`
	echo "$sLast" | tr '[A-Z0-9]' '-'
	echo "$sLast"
fi
