#!/bin/bash

#######################################################
### Created by khan on Mon Oct 17 12:13:38 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: DisableLoginSounds
#######################################################
if (( $# < 0 )) || [[ "$1" == *-h* ]]; then echo
sed -n "/^# Usa/,/^##*$/p" $0 | tr -d "#"; exit 0; fi
#######################################################

locate canberra | grep sound | while read file; do sudo sed -i '/gtk-play/d' $file; done
