#!/bin/bash
#./moveMouse $1 $2
#./clickDown
m=$(( echo "scale=10; ( $4 - $2 / ( $3 - $1 )" | bc ))
#dx=$( echo "scale=5; .2 / ( $3 - $2 )" | bc)
#        for x in {$1..$3};
#        do
	#	./moveMouse $x
#		y=$( echo "$m * ($x - $1) + $2" | bc )
#                echo "$x $y"
#		sleep $dt
#        done  
#sleep 1
#./moveMouse $3 $4
#./clickUp
