#!/bin/bash

function FindFile()
{
	if test -e "$1"; then
		echo "$1"
	elif which "$1"; then
		return
	elif locate -eir "/$1$" | head -n 1; then
		return
	else
		find `pwd` -maxdepth 1 -type f -name "$1" | head -n 1
	fi
}

for query in "$@"; do
	fullpathname $(FindFile "$query")
done
