#!/bin/bash

######################################################
### Created by khan on Fri Mar 2 16:48:02 CST 2012 ###
######################################################

##################### Help Text #####################
# Usage: FindKey

######################################################
if (( $# < 0 )) || [[ "$1" == --help ]]; then echo
sed -n "/^# Usa/,/^##*$/p" $0 | tr -d "#"; exit 0; fi
######################################################

## Initialize

## Functions

## Main
for sDir in /apps /desktop; do
	gconftool $sDir --all-dirs --dump | grep -B 3 $@
done | sed -n 's,<\(.*\)>\(.*\)<.*,\1 \2,p' | column -t
