#!/bin/bash

#####################################################
## Created by khan on Wed May 25 11:35:35 CDT 2011 ##
#####################################################

minargs=0; usage="Usage: `basename $0`"
if regmatch "$1" "^[\-]*h[^ ]*$" || [ "$#" -lt "$minargs" ]
then echo $usage; exit 0; fi

alltray firefox &

