#!/bin/bash

#####################################################
## Created by khan on Wed May  4 18:18:27 CDT 2011 ##
#####################################################
sudo echo "options snd-hda-intel model=mbp55" >> /etc/modprobe.d/alsa-base.conf

echo Reboot.

