#!/bin/bash

#####################################################
## Created by khan on Mon Apr 11 15:12:11 CDT 2011 ##
#####################################################

WaitForWindow -t 20 -w GnoMenu hidewindow

