#!/bin/bash

#####################################################
## Created by khan on Tue Apr 19 21:04:16 CDT 2011 ##
#####################################################

if [ $# == 0 ]; then
	 echo "Usage: $0" 
	 exit 0
fi

host=$1

if [ `ssh -o BatchMode=yes $host echo -n 2>&1 | grep -ic 'Offending key'` -gt 0 ]; then
	ssh-keygen -R $host
	ssh $host echo -n 
fi

