#!/bin/bash

#######################################################
### Created by khan on Mon Jul 18 00:30:07 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: FixOfaid
#######################################################
if (( $# < 0 )) || [[ "$1" == *-h* ]]; then echo
	grep -A 99999 "# Help.*#*" $0 |\
	grep -E -m 2 -B 99999 "#{10,}"
echo; exit 0; fi
#######################################################

for i in {1..5}; do
	WaitForWindow -t 20 -w Error -x "xdotool windowactivate '$xId' key alt+o; killall gnome-panel"
done
