#!/bin/bash

#######################################################
### Created by khan on Thu Nov 17 11:37:38 CST 2011 ###
#######################################################

###################### Help Text ######################
# Usage: FixPulseAudioNice
#######################################################
if (( $# < 0 )) || [[ "$1" == --help ]]; then echo
sed -n "/^# Usa/,/^##*$/p" $0 | tr -d "#"; exit 0; fi
#######################################################

## Initialize

## Functions

## Main

for iPID in `pgrep '(pulseaudio|udev|udisk)'`; do
	renice 0 -p $iPID
done
