#!/bin/bash

## Created by khan on Mon Apr 25 18:23:01 CDT 2011 ##

#if [ $# == 0 ]; then echo "Usage: $0"; exit 0; fi

sed 's/^\([0-9]*\)\./[\1\]/g' Refs | sed 's/;\([0-9]*.*\):\([0-9]*.*\)\./; \1: \2./' > Refs2
grep ';[0-9]' Refs2

