#!/bin/bash

######################################################
### Created by khan on Thu Feb 2 05:46:00 CST 2012 ###
######################################################

##################### Help Text #####################
# Usage: FixTouchpad

######################################################
if (( $# < 0 )) || [[ "$1" == --help ]]; then echo
sed -n "/^# Usa/,/^##*$/p" $0 | tr -d "#"; exit 0; fi
######################################################

## Initialize

## Functions

## Main
gconftool-2 --set --type boolean /desktop/gnome/peripherals/touchpad/touchpad_enabled
