#!/bin/bash

######################################################
### Created by khan on Tue Oct 4 22:08:19 CDT 2011 ###
######################################################

##################### Help Text #####################
# Usage: foreach
######################################################
if (( $# < 0 )) || [[ "$1" == *-h* ]]; then echo
	grep -A 99999 "# Help.*#*" $0 |\
	grep -E -m 2 -B 99999 "#{10,}"; echo; exit 0
fi
######################################################

function ForEachArgOf()
{
	while (($# > 0)); do
		"$1" "$line"
		shift
	done
}

while read line; do
	ForEachArgOf "$@"
done
