#!/bin/bash

#######################################################
### Created by khan on Tue Jun 14 12:46:30 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: getlinks
#######################################################

function OneLink() {
	query="$2"
	AllLinks "$@" | grep "$query" | head -n 1
}

case $# in
	1) AllLinks "$@"
	;;
	
	2) OneLink "$@"
	;;
	
	3) $3 `OneLink "$@"`
	;;
esac

