#!/bin/bash

#####################################################
## Created by khan on Thu May 26 22:25:11 CDT 2011 ##
#####################################################

minargs=0; usage="Usage: `basename $0`"
if regmatch "$1" "^[\-]*h[^ ]*$" || [ "$#" -lt "$minargs" ]
then echo $usage; exit 0; fi

echo Getting firewall rules...

ruleF=/tmp/rules.txt
sudo iptables -L | tee $ruleF