#!/bin/bash

#######################################################
### Created by khan on Fri Oct 19 10:51:57 CDT 2012 ###
#######################################################

###################### Help Text ######################
# Usage: GPA2Grade

#######################################################
if (( $# < 0 )) || [[ "$1" == --help ]]; then echo
sed -n "/^# Usa/,/^##*$/p" $0 | tr -d "#"; exit 0; fi
#######################################################

## Initialize

## Functions

## Main
g=`Round $1 | tr '01234' 'FDCBA'`
echo -n $g

g6=`echo "scale=5; 6 * ( $1 - $g )" | bc`
if (($(echo "scale=5; $g6 > 1" | bc) == 1 )); then echo +; fi
if (($(echo "scale=5; $g6 < -1" | bc) == 1 )); then echo -; fi
