#!/bin/bash
dir=`pwd`
flags="-avzHu $@ --exclude '*~' -e ssh"
host="khan@$gauss"
echo Uploading from $dir to $host...
#echo rsync $flags $dir $host:`dirname $dir`
rsync $flags $dir $host:`dirname $dir`

