#!/bin/bash

######################################################
### Created by khan on Wed Nov 2 16:53:35 CDT 2011 ###
######################################################

##################### Help Text #####################
# Usage: HiddenFilesMac
######################################################
if (( $# < 0 )) || [[ "$1" == *-h* ]]; then echo
sed -n "/^# Usa/,/^##*$/p" $0 | tr -d "#"; exit 0; fi
######################################################


if [[ `defaults read com.apple.Finder AppleShowAllFiles` == TRUE ]]; then
	defaults write com.apple.Finder AppleShowAllFiles FALSE
else
	defaults write com.apple.Finder AppleShowAllFiles TRUE
fi

killall Finder