#!/bin/bash

#######################################################
### Created by khan on Tue Dec 17 19:22:21 CST 2013 ###
#######################################################

###################### Help Text ######################
# Usage: isConn

#######################################################
if (( $# < 0 )) || [[ "$1" == --help ]]; then echo
sed -n "/^# Usa/,/^##*$/p" $0 | tr -d "#"; exit 0; fi
#######################################################

## Initialize

## Functions

## Main
#!/bin/bash

WGET="/usr/bin/wget"

$WGET -q --tries=4 --timeout=7 http://www.google.com -O /tmp/google.idx &> /dev/null
if [ ! -s /tmp/google.idx ]; then
	echo "No internet connection." > /dev/stderr
	exit 1
fi
