#!/bin/bash

#####################################################
## Created by khan on Mon May  9 16:49:29 CDT 2011 ##
#####################################################

minargs=0; usage="Usage: $0"
if string "^[\-]*h[^ ]*$" is in "$1" || [ "$#" -lt "$minargs" ]
then echo "Usage: $0"; exit 0; fi

if isAlive "$1"; then exit 1; else exit 0; fi

