#!/bin/bash

#######################################################
### Created by khan on Thu May 26 22:29:08 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: isEmpty <string> or <file>
# also accepts piped input."
#######################################################
if (( $# < 0 )) || [[ "$1" == *-h* ]]; then echo
	grep -A 99999 "# Help.*#*" $0 |\
	grep -E -m 2 -B 99999 "#{10,}"; echo; exit 0
fi
#######################################################

if [ $# -gt 1 ]; then exit 1; fi

# Multiple line pipe
if pipe; then
	iOut=1
	while read -t 1 line; do
		isEmpty "$line"
		iOut=$(( $iOut * ! $? ))
	done
	exit $(( ! $iOut ))
fi

# Multiple line argument
nInput=`echo $@ | wc -l`
if ((nInput > 1)); then
	echo $@ | isEmpty
	exit $?
fi

# Empty file
if [ -f "$1" ]; then
	if ((`FileSize "$1"` == 0)); then
		exit 0
	else
		exit 1
	fi
else
	# Empty string
	if [ "$1" == "" ]; then
		exit 0
	else
		exit 1
	fi
	
fi

