#!/bin/bash

#####################################################
## Created by khan on Sun Jun  5 09:08:09 CDT 2011 ##
#####################################################

minargs=0; usage="Usage: `basename $0`"
if regmatch "$1" "^[\-]*h[^ ]*$" || [ "$#" -lt "$minargs" ]
then echo $usage; exit 0; fi

if [ $# -gt 0 ] && [ cd "$@" 2> /dev/null]; then
	exit 

