#!/bin/bash

#######################################################
### Created by khan on Mon Dec 10 01:37:34 CST 2012 ###
#######################################################

###################### Help Text ######################
# Usage: jnc

#######################################################
if (( $# < 0 )) || [[ "$1" == --help ]]; then echo
sed -n "/^# Usa/,/^##*$/p" $0 | tr -d "#"; exit 0; fi
#######################################################

## Initialize

## Functions

## Main
java -jar /opt/TigerVNC/vnc/classes/VncViewer.jar -passwd $HOME/.vnc/passwd $@
