#!/bin/bash

#####################################################
## Created by khan on Wed May  4 11:09:18 CDT 2011 ##
#####################################################

while true
do
	/usr/bin/emerald --replace
done

