#!/bin/bash

#####################################################
## Created by khan on Fri Apr 29 12:16:09 CDT 2011 ##
#####################################################

minargs=0
if [ "$1" == "--help" ] || [ "$1" == "-h" ] || [ "$#" -lt "$minargs" ]; then echo "Usage: $0"; exit 0; fi

KeepAlive emerald --replace

