#!/bin/bash

#######################################################
### Created by khan on Thu Nov 15 22:17:30 CST 2012 ###
#######################################################

###################### Help Text ######################
# Usage:  ###################### Help Text ###################### script=`basename $0` Usage="Usage: $script" if isHelp 0 $0 "$@"; then echo $Usage; exit 0; fi #######################################################  Usage: StripPath  ###################### Help Text ###################### script=`basename $0` Usage="Usage: $script" if isHelp 0 $0 "$@"; then echo $Usage; exit 0; fi #######################################################  Usage: StripPath

#######################################################
if (( $# < 0 )) || [[ "$1" == --help ]]; then echo
sed -n "/^# Usa/,/^##*$/p" $0 | tr -d "#"; exit 0; fi
#######################################################

## Initialize

## Functions

## Main
while read host; do
	if isAlive $host; then echo $host; fi
done
