#!/bin/bash

#######################################################
### Created by khan on Tue Jul 26 01:18:18 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: LoadTiger
#######################################################
if (( $# < 0 )) || [[ "$1" == *-h* ]]; then echo
	grep -A 99999 "# Help.*#*" $0 |\
	grep -E -m 2 -B 99999 "#{10,}"
echo; exit 0; fi
#######################################################

	pConf=$HOME/.vnc/`cat $HOME/.vnc/session`/tiger.conf
	sed 's/ *= */=/g' $pConf |\
	while read line; do
		eval $line
	done

