#!/bin/bash

#####################################################
## Created by khan on Thu May 26 13:51:24 CDT 2011 ##
#####################################################

minargs=0; usage="Usage: `basename $0`"
if regmatch "$1" "^[\-]*h[^ ]*$" || [ "$#" -lt "$minargs" ]
then echo $usage; exit 0; fi

echo '
set front_app to (path to frontmost application as Unicode text)

tell application "X11"
    activate
    set position of window '$1' to {0, 0}
end tell' | osascript

