#!/bin/bash
xMax=`xMax`
yMax=`yMax`

if [[ $1 < 0 ]]; then
	(( x = $xMax + $1 ))
else
	x=$1
fi	
if [[ $2 < 0 ]]; then
	(( y = $yMax + $2 ))
else
	y=$2
fi	
if [ $# == 4 ]; then
	if [ `isPositive $3` == "0" ]; then
		(( x = `echo "( (1 + $3) * $xMax ) + $x" | bc | awk '{printf("%d\n",$1 + 0.5)}'` ))
	else
		(( x = `echo "( $3 * $xMax ) + $x" | bc | awk '{printf("%d\n",$1 + 0.5)}'` ))
	fi
	if [ `isPositive $4` == "0" ]; then
		(( y = `echo "( (1 + $4) * $yMax ) + $y" | bc | awk '{printf("%d\n",$1 + 0.5)}'` ))
	else
		(( y = `echo "( $4 * $yMax ) + $y" | bc | awk '{printf("%d\n",$1 + 0.5)}'` ))
	fi
fi	
echo "MotionNotify $x $y" | xmacroplay -d 0:0 &> /dev/null
#xdotool mousemove $x $y
