#!/bin/bash

#####################################################
## Created by khan on Sun Jun  5 22:17:04 CDT 2011 ##
#####################################################

Usage="Usage: `basename $0`"

if isHelp 0 $0 "$@"; then
	echo $Usage; exit 0
fi

sudo smbmount //riogrande.cps.utexas.edu/HIRBIL/Users/khan ~/riogrande -o credentials=$HOME/.smb/riogrande

