#!/bin/bash

#####################################################
## Created by khan on Tue May 10 12:32:31 CDT 2011 ##
#####################################################

minargs=1; usage="Usage: $0"
if string "^[\-]*h[^ ]*$" is in "$1" || [ "$#" -lt "$minargs" ]
then echo "Usage: $0"; exit 0; fi

name=$1

while [ -e $name ]; do
	num=`echo $name | grep -o '[0-9]*$'`	
	name=`echo $name | sed "s/[0-9]*$/$(( ++num ))/g"`
done

echo $name

