#!/bin/bash

pObj=`TempFile .obj`
cat /dev/stdin > $pObj &

	nVert=`grep -c '^v ' $pObj`
	nTris=`grep -c '^f ' $pObj`
	
	# Header line
	echo $nVert $nTris
	
	# Vertices
	sed -n 's/^v //p' $pObj
	
	# Vertices and normals
	#	paste -d ' ' <(sed -n 's/^v //p' $pObj) <(sed -n 's/^vn //p' $pObj) >> $pRaw
	
	# Triangle list
	grep '^f ' $pObj | awk '{print $2-1,$3-1,$4-1}'
rm $pObj
