#!/bin/bash

#####################################################
## Created by khan on Mon Jun  6 13:44:32 CDT 2011 ##
#####################################################

# Initialization
sProg="$1"; shift; pFile="$@"

# Main
playonlinux --run "Microsoft $sProg 2007" "$pFile"

# Move any printed PDFs
if [ `ls $HOME/PDF | wc -l` -gt 0 ]; then
	cupsPDFrenamer `winfullname "$pFile"`
fi
