#!/bin/bash

#######################################################
### Created by khan on Wed Jun 15 10:04:37 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: other
# Shows second location for command name
#######################################################
if isHelp 0 $0 "$@"; then exit 0; fi
which -a $@ | uniq | sed -n 2p

