#!/bin/bash
a=`ping -q -c 1 -w 2 $@ | grep received`
ac=`ping -q -c 1 -w 2 $@ | grep -ic received`
if [ $ac == 0 ]; then
	echo 0
else
	t=`echo $a | awk '{print $4}'`
	if [ $t == 0 ]; then
		echo 0
	elif [ $t == 1 ]; then
		echo 1
	elif [ $t == 2 ]; then
		echo 1
	else
		echo 0
	fi
fi

