#!/bin/bash
for i in $(seq 1 $1);

do 
	echo "KeyStrPress Return" | xmacroplay -d 0:0 &> /dev/null
	echo "KeyStrRelease Return" | xmacroplay -d 0:0 &> /dev/null
	if [ $# == 2 ]; then
		sleep $2
	fi
done
