#!/bin/bash

######################################################
### Created by khan on Mon Nov 7 14:12:54 CST 2011 ###
######################################################

##################### Help Text #####################
# Usage: Print <file> <lpoptions> [-p printer]
######################################################
if (( $# < 1 )) || [[ "$1" == *-h* ]]; then echo
sed -n "/^# Usa/,/^##*$/p" $0 | tr -d "#"; exit 0; fi
######################################################

## Arguments
pFile=`echo $@ | sed 's/ -.*//g'`
sArgs=`echo $@ | sed -n 's/.* -/-/p'`
sPrinter=`echo $@ | sed -n 's/.*-[pP] \([^ ]*\).*/\1/p' | xargs PrinterName`

## Defaults

## Initialize
sOpts="$sArgs -o sides=two-sided-long-edge -P"

## Main
lpr $pFile $sOpts $sPrinter
