#!/bin/bash
## MAIN
	read sHeader;
	nVerts=${sHeader%% *}; nTris=${sHeader##* }
	
	echo "# Created by raw2obj (Author: Rez Khan)"
	echo "# Converted RAW to OBJ format."
	echo "# Number of vertices, triangles: $nVerts $nTris"
	
	head -n $nVerts | awk '{print "v",$1,$2,$3}'
	tail -n $nTris  | awk '{print "f",$1+1,$2+1,$3+1}'
