#!/bin/bash

#######################################################
### Created by khan on Thu Dec 26 16:08:57 PST 2013 ###
#######################################################

###################### Help Text ######################
# Usage: ReadSNPs

#######################################################
if (( $# < 0 )) || [[ "$1" == --help ]]; then echo
sed -n "/^# Usa/,/^##*$/p" $0 | tr -d "#"; exit 0; fi
#######################################################

## Initialize

## Functions
function Names()
{
	ls ~/genomes/*.zip | sed 's/.*genome_//' | grep -o '^..' | tr '\n' '\t'
	echo
}

function GetAlleles()
{
	sSNP=$1
	sSNP="rs${sSNP/rs/}"
	
	if ! zgrep $sSNP'[^0-9]' ~/genomes/*.zip; then
		find ~/genomes/*.zip | while read line; do
			echo "--"
		done
	fi | awk '{print $NF}'
	echo
}

## Main
Names
cat "$1" | awk '{print $1}' | while read snp; do
	GetAlleles $snp
done

#	awk 'sub(FS $NF,x)'
