#!/bin/bash

#######################################################
### Created by khan on Wed May 11 09:33:32 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: regmatch <string> <pattern>
#######################################################
if [[ "$1" == *-h* ]]; then echo
	grep -A 99999 "# Help.*#*" $0 |\
	grep -E -m 2 -B 99999 "#{10,}"
echo; exit 0; fi
#######################################################

if (( $# < 2 )); then exit 1; fi

if [[ "$1" == "-v" ]]; then bVerbose=true; shift; fi

if test -z "$2"; then
	test -z "$1"
else
	echo "$1" | grep -Eq "$2"
fi
val=$?

if [[ $bVerbose == true ]]; then
	tester [ $val == 0 ]
fi

exit $val
