#!/bin/bash

######################################################
### Created by khan on Wed Oct 5 20:16:40 CDT 2011 ###
######################################################

##################### Help Text #####################
# Usage: RemoveMacFiles <dir>
######################################################
if (( $# < 0 )) || [[ "$1" == *-h* ]]; then echo
	grep -A 99999 "# Help.*#*" $0 |\
	grep -E -m 2 -B 99999 "#{10,}"; echo; exit 0
fi
######################################################

pFiles=/export/data/software/databases/MacResources.txt

# Update the database of suspected Mac files
if (( $# > 0 )); then
	FindResourceFiles $@ | tee $pFiles
fi

# Remove all mac files indicated in $pFiles
sed -n 's/^ *true *: *//p' "$pFiles" | xargs rm -rvf
