#!/bin/bash

#######################################################
### Created by khan on Wed Oct 17 21:55:26 CDT 2012 ###
#######################################################

###################### Help Text ######################
# Usage: RemoveBadLinks <dir>
#######################################################
if (( $# < 0 )) || [[ "$1" == --help ]]; then echo
sed -n "/^# Usa/,/^##*$/p" $0 | tr -d "#"; exit 0; fi
#######################################################

## Initialize
cwd=`pwd`
pDir=${@:-`pwd`}
cd `fileparts 1 "$pDir"`

## Functions

## Main
ls -1rsdSH * | grep '^ *0 ' | awk '{print $2}' | xargs rm
