#!/bin/bash

#######################################################
### Created by khan on Sat Jul 2 12:20:52 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: repeat <n> <command>
#######################################################
if isHelp 2 $0 "$@"; then exit 0; fi

nReps=$1; shift

for (( iRep=0; iRep < nReps; iRep++ )); do
	eval "$@"
done
