#!/bin/bash
if [ $# == 0 ]; then
	echo "Usage: $0 <fileToReplaceText in> <file with keywords>"
else
	cat $2 | while read line;
	do
		a=${line};
		read nextline;
		b=${nextline};
		replace $b "${a}" $1
		if [ ${#b} == 10 ]; then
			j=${b:0:3}-${b:3:3}-${b:6:4}
		elif [ ${#b} == 11 ]; then
			j=${b:1:3}-${b:4:3}-${b:7:4}
		else
			j=${b:0:3}-${b:3:4}
			jk=253-${b:0:3}-${b:3:4}
			replace "$jk" "${a}" $1
		fi
		replace "$j" "${a}" $1
	done
fi
