#!/bin/bash

#####################################################
## Created by khan on Thu Apr  7 17:28:42 CDT 2011 ##
#####################################################

if [ $# == 0 ]; then
	echo "Usage: ResetBadApplet <Applet Name> <Size Limit in MB>"
	exit 0
fi

if [ "$1" == "all" ]; then
	ResetBadApplet nm-applet $2
	ResetBadApplet indicator-applet $2
	exit 0
fi

if [ $# == 1 ]; then 
	mblimit=40 # MB
else
	mblimit=$2
fi

mem=`ps -eo rss,cmd | egrep 'nm-applet( |$)' | grep -v $0 | grep -v grep | awk '{print $1}' | sort | tail -n1`

if [ "$mem" == "" ]; then mem=0; fi
	
mem=`echo $mem / 1000 | bc`
if [ `echo "$mem > $mblimit" | bc` -gt 0 ]; then
	$1 was found to occupy $mem MB. This is greater than $mblimit, so it will be terminated.
	killall "$1"
	sleep 4 ; "$1" &
fi

