#!/bin/bash

#######################################################
### Created by khan on Wed Sep 11 01:39:46 CDT 2013 ###
#######################################################

###################### Help Text ######################
# Usage: RightClick

#######################################################
if (( $# < 0 )) || [[ "$1" == --help ]]; then echo
sed -n "/^# Usa/,/^##*$/p" $0 | tr -d "#"; exit 0; fi
#######################################################

## Initialize

## Functions

## Main
(echo ButtonPress 3; echo ButtonRelease 3) | xmacroplay -d 2:0 >/dev/null
