#!/bin/bash

if [ $# == 0 ]; then
	echo "Usage: rmAll <files>"
	exit 0
fi

if [ "$1" == "-f" ]; then
	syncAll
	rm -rf $@
	syncUp --delete
else
	rm -rf $@
	while [[ "$1" == -* ]]; do shift; done
	touch "$@"
	syncUp
fi

