#!/bin/bash

######################################################
### Created by khan on Thu Oct 6 11:04:31 CDT 2011 ###
######################################################

##################### Help Text #####################
# Usage: rmBadLinks
######################################################
if (( $# < 0 )) || [[ "$1" == *-h* ]]; then echo
	grep -A 99999 "# Help.*#*" $0 |\
	grep -E -m 2 -B 99999 "#{10,}"; echo; exit 0
fi
######################################################

if [ $# == 0 ]; then
	if isHost sandstone; then
		set /usr/local/bin
	fi
fi

find -L `fileparts 1 $@` -type l -exec rm -f {} \;
