#!/bin/bash

######################################################
### Created by khan on Sun Nov 6 21:26:14 CST 2011 ###
######################################################

##################### Help Text #####################
# Usage: rmount
######################################################
if (( $# < 0 )) || [[ "$1" == *-h* ]]; then echo
sed -n "/^# Usa/,/^##*$/p" $0 | tr -d "#"; exit 0; fi
######################################################

## Arguments
sName=$1

## Initialize
sDir=/home/khan/$sName

## Main
case $sName in
	hirbil)
		if isHost sandstone; then
			mkdir -p $sDir
			if ! mount | word 3 | grep -q $sDir; then
				smbmount //riogrande.cps.utexas.edu/HIRBIL $sDir -o credientials=~/.smbpasswd
			fi
		else
			ssh sandstone "rmount $sName"
			sshfs sandstone:$sName $sDir
		fi
	;;
	*) sshfs ${sName}: ~/$sName ;;
esac
