#!/bin/bash

#######################################################
### Created by khan on Sat Oct 15 22:09:31 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: rmpath <path>
#######################################################
if (( $# < 0 )) || [[ "$1" == *-h* ]]; then echo
	grep -A 99999 "# Help.*#*" $0 |\
	grep -E -m 2 -B 99999 "#{10,}"; echo; exit 0
fi
#######################################################

newpath=$PATH
for path in "$@"; do
	newpath=`echo $newpath | tr : '\n' | grep -vx "$path" | tr '\n' : | sed 's/:$/\n/g'`
done
echo "export PATH=$newpath"

