#!/bin/bash

#######################################################
### Created by khan on Tue Jul 19 22:29:39 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: rover
#######################################################
if (( $# < 0 )) || [[ "$1" == *-h* ]]; then echo
	grep -A 99999 "# Help.*#*" $0 |\
	grep -E -m 2 -B 99999 "#{10,}"
echo; exit 0; fi
#######################################################

vglrun VolumeRover &
WaitForWindow -w Choose the location of the cache directory -x 'xdotool windowactivate $xId'
#xdotool type /tmp
xdotool key Return

WaitForWindow -w "Volume Rover" -x 'xdotool windowactivate $xId'

for file in "$@"; do
	if [[ `Ext $file` == .mrc ]]; then
		xdotool key ctrl+o
		WaitForWindow -w Open -x 'xdotool windowactivate $xId'
		xdotool type "$file"
		#				xdotool key Return
	fi
done

rm -rf VolumeCache
