#!/bin/bash

#######################################################
### Created by khan on Thu Oct 13 08:42:25 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: rsense [ fan | tmp | test ]
#######################################################
if (( $# < 1 )) || [[ "$1" == *-h* ]]; then echo
	grep -A 99999 "# Help.*#*" $0 |\
	grep -E -m 2 -B 99999 "#{10,}"; echo; exit 0
fi
#######################################################

case $1 in
	[Ff]an)
		sudo mkdev.sh
		sudo sdt | grep -i fan | awk '{print $NF}' | tee /tmp/o
	;;
	[Tt]*mp)
		sensors | sed -n 's/temp1: *+\([0-9\.]*\).*/\1/p'
	;;
	test)	for ii in {1..8}; do echo 9999999; done ;;
	*) rsense ;;
esac


