#!/bin/bash

#####################################################
## Created by khan on Fri Apr 15 17:46:19 EDT 2011 ##
#####################################################

if isMac; then
	date +%s
else
	date +%s.%N
fi

