#!/bin/bash

#######################################################
### Created by khan on Thu Oct 13 10:32:55 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: SenseAlarm [fan|temp|test] <limit> <interval s>
# SenseAlarm temp 55 30
# sudo SenseAlarm fan 9000 120
#######################################################
if (( $# < 0 )) || [[ "$1" == *-h* ]]; then echo
	grep -A 99999 "# Help.*#*" $0 |\
	grep -E -m 2 -B 99999 "#{10,}"; echo; exit 0
fi
#######################################################

sType=${1:-tmp}

# Degrees celcisus threshold
maxtemp=${2:-55}

iInterval=${3:-30}

while true; do
	for temp in `rsense $sType`; do
		if (( `echo "$temp > $maxtemp" | bc` == 1 )); then
			# Sound Alarm
			rsense $sType | mail -s "Rez" reswanul@gmail.com -c ress@mail.utexas.edu;
			exit 0
		fi
	done
	sleep $iInterval
done
