#!/bin/bash

#####################################################
## Created by khan on Wed May 11 21:09:52 CDT 2011 ##
#####################################################
# Serves current dir on port 8000

minargs=0; usage="Usage: $0"
if string "^[\-]*h[^ ]*$" is in "$1" || [ "$#" -lt "$minargs" ]
then echo "Usage: $0"; exit 0; fi

python -m SimpleHTTPServer

