#!/bin/bash

#######################################################
### Created by khan on Tue Oct 23 21:22:03 CDT 2012 ###
#######################################################

###################### Help Text ######################
# Usage: SetMouseProp

#######################################################
if (( $# < 0 )) || [[ "$1" == --help ]]; then echo
sed -n "/^# Usa/,/^##*$/p" $0 | tr -d "#"; exit 0; fi
#######################################################

#	Device Accel Constant Deceleration (262):	1.000000
#	Device Accel Adaptive Deceleration (263):	20.000000
#	Device Accel Velocity Scaling (264):	19.000000

## Initialize
sProp="$1"; iDev="$2"; xVal="$3"

## Functions

## Main
if ! isInt "$iDev"; then
	iDev=`xinput | grep "$iDev" | cut -d= -f2 | awk '{print $1}'`
fi
iProp=`xinput -list-props $iDev | grep -i "$sProp" | word 2 '()'`
xinput set-prop $iDev $iProp $xVal
