#!/bin/bash

######################################################
### Created by khan on Wed Nov 2 09:59:36 CDT 2011 ###
######################################################

##################### Help Text #####################
# Usage: setmap
######################################################
if (( $# < 0 )) || [[ "$1" == *-h* ]]; then echo
sed -n "/^# Usa/,/^##*$/p" $0 | tr -d "#"; exit 0; fi
######################################################
echo -n "rules: "
setxkbmap -print | sed -n 's/.*include .\([a-z0-9]*\)+aliases.*/\1/p'
echo -n "model: "
setxkbmap -print | grep xkb_geometry | word 2 '(' | word 1 ')'

