#!/bin/bash

#######################################################
### Created by khan on Fri Jun 17 22:22:15 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: SetWinSize
#######################################################
if (( $# < 0 )) || [[ "$1" == *-h* ]]; then echo
	grep -A 99999 "# Help.*#*" $0 |\
	grep -E -m 2 -B 99999 "#{10,}"; echo; exit 0
fi
#######################################################

case $# in
	2)	sWin=`ActiveWindowID` 	;;
	3)	sWin="$1"; shift		;;
esac

w="$1"
h="$2"

xdotool windowsize  "$sWin" $((w-1)) $h
xdotool windowsize  "$sWin" $w $h
