#!/bin/bash

#####################################################
## Created by khan on Mon Apr 18 21:12:14 CDT 2011 ##
#####################################################

if [ `ssh-add -l 2>&1 | grep -ic identities` -gt 0 ]; then
	. ssh-start
fi

