#!/bin/bash

#####################################################
## Created by khan on Tue Apr 19 13:23:22 CDT 2011 ##
#####################################################

host=$@
scanner=UT_AUS_3TMR
transfer=transfer

if [ $# == 0 ]; then echo "Usage: $0"; exit 0; fi

#if [ "`echo $host | grep -ic projects:`" -gt 0 ]; then
#	host=`echo $host | sed 's/projects[:]+/sandstone:/projects/'`
#fi

case $host in
	sandstone*)
		if [[ "$scanner" == `hostname` ]]; then
			echo -p 10000 -o HostKeyAlias=sandstone `echo $host | sed 's/[^ ]*[@]*sandstone.*/sdc@transfer/'`
		else
			echo $host | sed 's/sandstone[.irc.utexas.edu]*$/sandstone.irc.utexas.edu/'
	fi ;;
	transfer*) echo -p 32768 -o HostKeyAlias=transfer `echo $host | sed 's/[^ ]*[@]*transfer/sdc@localhost/'` ;;
	software) echo sandstone.irc.utexas.edu:/export/data/software ;;
	mri) echo sandstone.irc.utexas.edu:/export/data/mri ;;
	*) echo $host ;;
esac

