#!/bin/bash
# $1 - $2 = $3
if [ $# == 0 ]; then
	echo "Subtract two data sets: A - B = C"
	echo "Usage: SubtractThreeColumnData <A> <B> <C>"
	#first col = time, other cols = {x, y}
else
	cat $1 | grep -v '#' > $1.temp
	cat $2 | grep -v '#' > $2.temp
	join $1.temp $2.temp | awk '{ print $1,"\t",$2-$4,"\t",$3-$5 }' > $3
	rm -f $1.temp $2.temp
fi

