#!/bin/bash

######################################################
### Created by khan on Sun Sep 8 14:27:46 CDT 2013 ###
######################################################

##################### Help Text #####################
# Usage: swapmouse

######################################################
if (( $# < 0 )) || [[ "$1" == --help ]]; then echo
sed -n "/^# Usa/,/^##*$/p" $0 | tr -d "#"; exit 0; fi
######################################################

## Initialize
sId=`xinput | grep -i Touchscreen | cut -d= -f2 | awk '{print $1}'`
#t0=`date +%s`

## Main
xinput set-button-map "$sId" 3 2 1 4 5

script -c "xinput test $sId" | while read line; do
	if echo "$line" | grep -q "button release"; then
		break;
		#	else
		#	t1=`date +%s`
		#t=`echo $t1 - $t0 | bc`
		#ti=`printf "%.0f\n" $t`
		#	exit 0
		#if (($ti>1)); then
		#	xinput set-button-map "$sId" 1 2 3 4 5
		#fi
	fi
done

xinput set-button-map "$sId" 1 2 3 4 5

w=`Displays 1 w`;
h=`Displays 1 h`;

s=`xinput list 9 | egrep 'Range|value' | head -n 4 | awk '{print $NF}' | tr '\n' ' '`

viCoords=`echo "$w $h $s" | awk '{print $1*$4/$3,$2*$6/$5}'`
xdotool mousemove --sync $viCoords click 3

#xdotool --sync click 1
#xdotool sleep 0.5 click 3

