#!/bin/bash

#####################################################
## Created by khan on Wed May  4 21:32:24 CDT 2011 ##
#####################################################

cd

if [ $# == 0 ]; then
	for host in `otherhosts`; do
		syncThemes $host
	done
else
	host=$1
	syncAll .emerald $host
	syncAll .themes $host
	syncAll .icons $host
fi

