#!/bin/bash

#######################################################
### Created by khan on Sun Sep 15 16:21:29 CDT 2013 ###
#######################################################

###################### Help Text ######################
# Usage: SyncMouse
#######################################################
if (( $# < 0 )) || [[ "$1" == --help ]]; then echo
sed -n "/^# Usa/,/^##*$/p" $0 | tr -d "#"; exit 0; fi
#######################################################

## Initialize
sId=`xinput | grep -i Touchscreen | cut -d= -f2 | awk '{print $1}'`
w=`Displays 1 w`
h=`Displays 1 h`
s=`xinput list 9 | egrep 'Range|value' | head -n 4 | awk '{print $NF}' | tr '\n' ' '`
viCoords=`echo "$w $h $s" | awk '{print $1*$4/$3,$2*$6/$5}'`

## Main
echo "$viCoords"

# Move mouse to touch location
xdotool mousemove --sync $viCoords
