#!/bin/bash

#######################################################
### Created by khan on Sat Jun 11 21:51:38 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: TempFifo <Filename>
#######################################################
if (( $# < 0 )) || [[ "$1" == --help ]]; then echo
sed -n "/^# Usa/,/^##*$/p" $0 | tr -d "#"; exit 0; fi
#######################################################

sName=`echo "$@" | sed 's/-[^ ]*//g'`
pFile="/tmp/`UniqueName`$sName"
mkfifo "$pFile"; echo "$pFile"

if disp "$@" | grep -q '\-p'; then
	tee > "$pFile"
fi
