#!/bin/bash

#######################################################
### Created by khan on Sat Jul 16 14:58:26 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: TermSplitHorz
#######################################################
if (( $# < 0 )) || [[ "$1" == *-h* ]]; then echo
	grep -A 99999 "# Help.*#*" $0 |\
	grep -E -m 2 -B 99999 "#{10,}"
echo; exit 0; fi
#######################################################
. $HOME/.bashrc

xdotool getactivewindow key shift+ctrl+o windowsize $(WinSize | awk '{print $1,'$1'*$2}')
