#!/bin/bash

#######################################################
### Created by khan on Mon Oct 17 21:56:01 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: TimePassed
#######################################################
if (( $# < 0 )) || [[ "$1" == *-h* ]]; then echo
sed -n "/^# Usa/,/^##*$/p" $0 | tr -d "#"; exit 0; fi
#######################################################

## Initialize
if [[ $1 == -* ]]; then
case $1 in
	-s) d=1;;
	-m) d=60;;
	 *) d=3600;;
esac
shift
else
	d=3600
fi

## Main
sFileDate=`TimeOf "$@"`

sFileSecs=`date --date="$sFileDate" +%s`
sCurrSecs=`date --date=now +%s`

## Output
echo "($sCurrSecs - $sFileSecs) / $d" | bc

