#!/bin/bash

#####################################################
## Created by khan on Wed May 11 08:36:01 CDT 2011 ##
#####################################################

minargs=1; usage="Usage: $0"
if string "^[\-]*h[^ ]*$" is in "$1" ] || [ "$#" -lt "$minargs" ]
then echo "Usage: $0"; exit 0; fi

if isMac; then
	echo $@ | sed 's,^/home,/Users,'
else
	echo $@ | sed 's,^/Users,/home,'
fi

