#!/bin/bash

#######################################################
### Created by khan on Sun Nov 27 13:26:32 CST 2011 ###
#######################################################

###################### Help Text ######################
# Usage: input | TransRange 2-3,5-end

#######################################################
if (( $# < 0 )) || [[ "$1" == --help ]]; then echo
sed -n "/^# Usa/,/^##*$/p" $0 | tr -d "#"; exit 0; fi
#######################################################

## Initialize
viRange=${1:-"0"}; shift
sDelim=`dquote ${1:-" "}`

## Functions
function Translate()
{
	echo "{FS=$sDelim; $viRange" | sed -e 's,\([0-9][0-9]*\),$\1,g' -e 's/$1-\([, ]\)/$0\1/g' \
	-e 's/-\([ ,]\)/-end\1/g' -e 's/\([ ,]\)-/\1end-/g' -e 's/end/$NF/g' \
	-e 's,$\([0-9NF]*\)-$\([0-9NF]*\),for (i=\1;i<=\2;i++) printf $i FS,g' \
	-e 's/,f/FS ; f/g' -e 's/i FS,/i FS; /g' -e 's/^ *//g' -e 's/\n/"\n"/g' \
	-e 's/,/ FS /g' -e 's/; \$/; printf $/g' |\
	tr '\n' ';'
	echo ' printf "\n"}'
}

## Main
Translate
awk "$(Translate)"
