#!/bin/bash

#######################################################
### Created by khan on Mon Jun 13 11:28:39 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: try <variable> <command>
# Usage: try <variable> <test> <value> <value>
#######################################################
if isHelp 0 $0 "$@"; then exit 0; fi

export k=88
eval $@

