#!/bin/bash

#####################################################
## Created by khan on Thu Apr 21 22:04:22 CDT 2011 ##
#####################################################

if [ $# == 0 ]; then echo "Usage: $0"; exit 0; fi

sshfs=sshfs

#eval `ParseHost $1`

rlogin=`ssh-host-trans $1`

if (( $# == 1 )); then
	ldir=$HOME/$rname
else
	ldir=$2
fi

if [ ! -e $ldir ]; then mkdir -p $ldir; fi

ldir=`cd $ldir; pwd`

if ! mount | grep -iq "$rhost.*on.*$ldir"; then
	shift 2
	$sshfs $rlogin $ldir $@
fi
