#!/bin/bash

#####################################################
## Created by khan on Wed Apr 27 00:40:49 CDT 2011 ##
#####################################################

unclutter -idle 3 -notclass Nautilus &

