#!/bin/bash

######################################################
### Created by khan on Thu Jul 7 17:14:55 CDT 2011 ###
######################################################

##################### Help Text #####################
# Usage: UserAgent
######################################################
if (( $# < 0 )) || [[ "$1" == *-h* ]]; then echo
	grep -A 99999 "# Help.*#*" $0 |\
	grep -E -m 2 -B 99999 "#{10,}"
echo; exit 0; fi
######################################################

if isMac; then
	echo -n "Intel "
	system_profiler SPSoftwareDataType | grep -o 'Mac OS X [^ ]*'
fi
