#!/bin/bash

#######################################################
### Created by khan on Thu Oct 20 21:04:29 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: user-ids
#######################################################
if (( $# < 0 )) || [[ "$1" == *-h* ]]; then echo
sed -n "/^# Usa/,/^##*$/p" $0 | tr -d "#"; exit 0; fi
#######################################################

pUsers=`TempFile User:s`
sed 's/\([^:]*\):x:\([^:]*\).*/\1=\2/g' /etc/passwd > $pUsers

for sName in `sys-ids`; do
	sed -i "/^${sName}=.*$/d" $pUsers
done

	sed -i "s/^$//g" $pUsers

cat $pUsers
