#!/bin/bash

######################################################
### Created by khan on Sun Nov 4 20:42:28 CST 2012 ###
######################################################

##################### Help Text #####################
# Usage: vnc-ssh

######################################################
if (( $# < 0 )) || [[ "$1" == --help ]]; then echo
sed -n "/^# Usa/,/^##*$/p" $0 | tr -d "#"; exit 0; fi
######################################################

## Initialize

## Functions

## Main
#if ssh-add -l 2>&1 | grep -q Could; then
#	Starting ssh agent...
#	. ssh-agent bash
#fi

# Check if key exists
if [ ! -f ~/.ssh/id_rsa ]; then
	echo "Generating ssh key..."
	read -p "Enter a password of your choice:" sPass
	echo "echo $sPass" > $HOME/.sshp
	chmod u+rwx,go-rwx $HOME/.sshp
	ssh-keygen -N $sPass -f ~/.ssh/id_rsa
fi

# If no identities added
if ! ssh-add -l | grep -q $HOME; then
	pEnvir="$HOME/.ssh/environment"
	# Start agent if necessary
	if ! ps h -p `echo $SSH_AGENT_PID` &>/dev/null; then
		echo "Starting SSH agent..."
		if [ ! -f $pEnvir ]; then
			ssh-agent | grep -v echo > $pEnvir
			chmod a+rx "$pEnvir"
		fi
		. "$pEnvir"
	fi
	
	if ! ps h -p `echo $SSH_AGENT_PID` &>/dev/null; then
		ssh-agent | grep -v echo > $pEnvir
		chmod a+rx "$pEnvir"
		. "$pEnvir"
	fi
	
	# Add identity if necessary
	if ! /usr/bin/ssh-add -l | grep -q $HOME; then
		echo "Adding identity..."
		SSH_ASKPASS=$HOME/.sshp /usr/bin/ssh-add </dev/null
	fi
fi

pList=`mktemp -t plist.XXXXXX`
sList=`mktemp -t plist.XXXXXX`

# Validate
echo "Validate SSH connection..."

for server in `vnc-hosts`; do
pPass="$HOME/.vnc/$server/passwd"
if ! /usr/bin/ssh -o BatchMode=yes -o StrictHostKeyChecking=yes $server echo -n ; then
	ssh-fix-hosts $server
	echo "Uploading public key..."
	sPubFile=$HOME/.ssh/*.pub
	pubkey=`cat $sPubFile`
	/usr/bin/ssh $server "mkdir -p .ssh;
	echo $pubkey >> .ssh/authorized_keys;
	echo $pubkey >> .ssh/authorized_keys2;
	chmod go-w \$HOME;
	chmod -R u=rwx,go= .ssh;
	cd .ssh; chmod u=rw *;
	chmod go=r id_*.pub known_hosts"
fi
done
