#!/bin/bash

#######################################################
### Created by khan on Fri Jun 15 11:45:38 CDT 2012 ###
#######################################################

###################### Help Text ######################
# Usage: vnc-connect-edit

#######################################################
if (( $# < 0 )) || [[ "$1" == --help ]]; then echo
sed -n "/^# Usa/,/^##*$/p" $0 | tr -d "#"; exit 0; fi
#######################################################

## Initialize

## Functions

## Main
nano "$HOME/.vnc/tiger.conf"
vnc-connect-update
vnc-connect
