#!/bin/bash

#######################################################
### Created by khan on Thu Jun 14 11:38:56 CDT 2012 ###
#######################################################

###################### Help Text ######################
# Usage: Wait4Con

#######################################################
if (( $# < 0 )) || [[ "$1" == --help ]]; then echo
sed -n "/^# Usa/,/^##*$/p" $0 | tr -d "#"; exit 0; fi
#######################################################

## Initialize
sHost=$1

## Main
if ! isAlive $sHost; then
	echo "Failed to connect to $sHost. Waiting for connection..."
	
	for ((ii=0; ii<60; ii++)); do
		if isAlive $sHost; then
			exit 0;
		else
			sleep 1
		fi
	done
	echo "Could not connect to $sHost. Exiting."
	exit 1
else
	exit 0
fi


