#!/bin/bash

#####################################################
## Created by khan on Fri May 27 12:30:43 CDT 2011 ##
#####################################################

minargs=0; usage="Usage: `basename $0`"
if regmatch "$1" "^[\-]*h[^ ]*$" || [ "$#" -lt "$minargs" ]
then echo $usage; exit 0; fi

id=`xget id`
id=`windowID khan`
factor=1.15
args=`wmctrl -lG | grep $id | awk '{print $1, $5*'$factor', $6}'`

echo xdotool windowsize $args
xdotool windowsize $args

