#!/bin/bash

if [ $# == 0 ]; then
	window=TigerVNC:
else
	window="$@"
fi

fullname=`waitfortree | grep "$window" | tail -n 1 | cut -d '"' -f 2`

if [ "$fullname" == "" ]; then
	exit 1
else
	echo $fullname
	exit 0
fi

