#!/bin/bash

#######################################################
### Created by khan on Sat Jul 2 14:31:31 CDT 2011 ###
#######################################################

###################### Help Text ######################
# Usage: xmr
#######################################################
#TimedPrompt 10

#if isHelp 0 $0 "$@"; then exit 0; fi

#if [ $# == 0 ]; then
pFile=/tmp/action.mac
#else
#	pFile="$1"
#fi

xmacrorec2 > $pFile
